server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    url: jdbc:postgresql://localhost:5454/customer
    username: 'javid'
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: 'true'
        format_sql: 'true'
    hibernate:
      ddl-auto: update

host:
  local: http://localhost
ports:
  fraud: 8081
api:
  v1: api/v1

customer:
  properties:
    urls:
      fraud-check: ${host.local}:${ports.fraud}/${api.v1}/fraud/{customerId}
