server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    url: jdbc:postgresql://postgres:5432/customer
    username: 'javid'
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: 'true'
        format_sql: 'true'
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    addresses: rabbitmq:5672

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true

# getting application ip and port from eureka by name in capital
application:
  fraud: http://FRAUD
api:
  v1: api/v1

customer:
  properties:
    urls:
      fraud-check: ${application.fraud}/${api.v1}/fraud/{customerId}
